---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
Page:
  extensions:
    - DivisionPage
Page_Controller:
  extensions:
    - DivisionPage_Controller
IsahResource:
  extensions:
    - Addressable
    - Geocodable
IPInfoCache:
  GeoPath: '/Users/dustin/Downloads/GeoLite2-City.mmdb'