---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
IsahResource:
  extensions:
    - Addressable
    - Geocodable
SSViewer: 
  rewrite_hash_links: false
CalendarEvent:
  extensions:
    - EventExtension
Calendar:
    timezone: America/Chicago
    language: EN