---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
Page:
  extensions:
    - DivisionPage
Page_Controller:
  extensions:
    - DivisionPage_Controller
SexualAssaultResource:
  extensions:
    - Addressable
    - Geocodable
